# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c62583ccebfbce360c82ccfb2b4a737b43c8366c81f5c0fadd02b3907f1531271d78a51edcfc00d125db20e95a9b2d0b005c94831d142dd463d51b0794a05dd

test:
  secret_key_base: 1e850f38dcdfd8a84d7ded845ef78fa85d057983ee524a0689faddb25706d0198252982877c35d6d4fb65a9577f879b24bfb24ae439816b2872d800948228437

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
